### ISSUE TITLE
Update meta, title, favicon etc

### ISSUE THREAD

**Issue by Nikomus** [neontribe/ca-hospice-hope#27]
## Description
The content in the `<head>` such as title, meta description and favicons should relate to Hospice Hope.

## Plan
- [x] Source content for description and agreed title
- [x] Make a favicon
- [x] Update the title and description (they're in the head)
- [x] Analytics UA code

**Comment by katjam** [comment]
@HedgehogHolly Can you please find out what the UA code is, make a favicon and ask Rose or propose some copy for the description and title tags in the head?

**Comment by katjam** [comment]
It's the text in the index.html that will need changing - easiest way will be to make an index per brand.

**Comment by Hoolean** [comment]
The title, meta description and favicon pertain to Hospice Hope.
![image](https://user-images.githubusercontent.com/2150762/63450792-b4ae9b80-c43a-11e9-98d7-3fe8401698e4.png)

The general `contemplating-action` banner image needs to be replaced with a more specific one for Hospice Hope but, as suggested by #42, this is outside the scope of this sprint.

When I have checked Google Analytics, I will be able to confirm that the Analytics UA code was specified correctly and will mark this issue as tested and ready.

**Comment by Hoolean** [comment]
Found the Analytics UA code in source and have confirmed that it is correct from observing live data in Google Analytics when I browse. That was the last meta tag I had to check, so I will mark this as tested and ready.
